"""change column type

Revision ID: a4d1b47d86bd
Revises: de2c69599e32
Create Date: 2026-03-11 07:28:49.949186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d1b47d86bd'
down_revision = 'de2c69599e32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
